# Generated by Django 5.1.7 on 2025-07-25 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=1)),
                ('question_short', models.CharField(max_length=200)),
                ('recommended_action', models.TextField(default='None')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_User',
            fields=[
                ('session_id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cluster_label', models.IntegerField(default=-1)),
                ('total_emission', models.FloatField(default=-1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('choice_num', models.FloatField(default=1.0)),
                ('assumption', models.FloatField(default=1.0)),
                ('scale', models.FloatField(default=1.0)),
                ('emission_factor', models.FloatField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.quiz_question')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.quiz_choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.quiz_question')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.quiz_user')),
            ],
        ),
    ]
