# Generated by Django 5.1.7 on 2025-03-31 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_quiz_choice_quiz_question_delete_compdemo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.quiz_choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.quiz_question')),
            ],
        ),
    ]
