# Generated by Django 5.1.7 on 2025-04-17 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_quiz_response_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_choice',
            name='assumption',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='quiz_choice',
            name='choice_num',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='quiz_choice',
            name='emission_factor',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='quiz_choice',
            name='scale',
            field=models.FloatField(default=1.0),
        ),
    ]
