# Generated by Django 5.1.7 on 2025-04-17 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_quiz_choice_assumption_quiz_choice_choice_num_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz_response',
            old_name='choice',
            new_name='choice_id',
        ),
        migrations.RenameField(
            model_name='quiz_response',
            old_name='question',
            new_name='question_id',
        ),
    ]
