# Generated by Django 5.1.7 on 2025-04-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_quiz_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_user',
            name='session_id',
            field=models.CharField(default=1111, editable=False, max_length=36),
            preserve_default=False,
        ),
    ]
