# Generated by Django 5.1.7 on 2025-04-17 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_choice_quiz_response_choice_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz_response',
            old_name='choice_id',
            new_name='choice',
        ),
        migrations.RenameField(
            model_name='quiz_response',
            old_name='question_id',
            new_name='question',
        ),
    ]
