# Generated by Django 5.1.7 on 2025-04-17 20:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_choice_id_quiz_response_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
