# Generated by Django 5.1.7 on 2025-04-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_quiz_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_question',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quiz_question',
            name='question_short',
            field=models.CharField(default='update', max_length=200),
            preserve_default=False,
        ),
    ]
