# Generated by Django 5.1.7 on 2025-04-22 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_quiz_question_order_quiz_question_question_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_response',
            name='session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.quiz_user'),
        ),
    ]
