# Generated by Django 5.1.7 on 2025-04-22 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_quiz_response_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_response',
            name='session_id',
            field=models.CharField(max_length=100),
        ),
    ]
