# Generated by Django 5.1.7 on 2025-04-22 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_quiz_response_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_response',
            name='session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.quiz_user'),
        ),
    ]
