# Generated by Django 5.1.7 on 2025-04-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_quiz_response_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_user',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1111, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz_user',
            name='session_id',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
