# Generated by Django 5.1.7 on 2025-04-22 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_quiz_user_id_alter_quiz_user_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz_user',
            name='id',
        ),
        migrations.AlterField(
            model_name='quiz_user',
            name='session_id',
            field=models.CharField(editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
