# Generated by Django 5.1.7 on 2025-04-26 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_quiz_user_id_alter_quiz_user_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_user',
            name='cluster_label',
            field=models.IntegerField(default=-1),
        ),
    ]
