# Generated by Django 5.1.7 on 2025-05-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_quiz_user_cluster_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_user',
            name='total_emission',
            field=models.FloatField(default=-1.0),
        ),
    ]
