# Generated by Django 5.1.7 on 2025-06-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_quiz_user_total_emission'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_question',
            name='recommended_action',
            field=models.TextField(default='None'),
        ),
    ]
